# Generated by Django 6.0.3 on 2026-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cycle_length',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_cycle_length',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_cycle_name',
            field=models.CharField(default='Week', max_length=50),
        ),
    ]
