# Generated by Django 6.0.3 on 2026-04-10 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_profile_cycle_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Daily Run', max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
