# Generated by Django 6.0.3 on 2026-04-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_activity_timestamp_alter_activity_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='total_time',
        ),
    ]
