# Generated by Django 6.0.3 on 2026-04-14 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_activity_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='shoe',
            new_name='default_shoe',
        ),
        migrations.AddField(
            model_name='segment',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.shoe'),
        ),
    ]
