# Generated by Django 6.0.3 on 2026-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_activity_user_alter_block_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
