# Generated by Django 6.0.3 on 2026-04-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_shoe_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='segment',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='training.shoe'),
        ),
    ]
