# Generated by Django 6.0.3 on 2026-04-27 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_shoe_options_alter_segment_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='init_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
