# Generated by Django 6.0.3 on 2026-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_shoe_init_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='distance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
