# Generated by Django 6.0.3 on 2026-04-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_segment_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-start']},
        ),
    ]
