# Generated by Django 6.0.3 on 2026-04-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_activity_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='distance',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='duration',
            new_name='time',
        ),
    ]
