# Generated by Django 6.0.3 on 2026-04-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_rename_distance_segment_mileage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='mileage',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='time',
            new_name='duration',
        ),
    ]
